"""The 17 gallery pieces ("creations") carried over from the WordPress site.

Slugs, titles, order and starting prices are exactly as published at
/creation/<slug>/ so every existing URL keeps working. Descriptions, alt text
and categories are new - written from the photographs themselves.

Each entry: slug, title, price (starting), category, image (basename under
/assets/img/gallery/), orientation, wording (the painted text), alt, blurb,
details (list of what is in the painting), palette (list of CSS colors),
published (date from the WordPress export).
"""

CATEGORIES = [
    ("birthday", "Birthday"),
    ("baby", "Baby & Family"),
    ("scripture", "Scripture & Verse"),
    ("church", "Children's Church"),
    ("seasonal", "Seasonal & Holiday"),
]

CREATIONS = [
    {
        "slug": "custom-hand-painted-birthday-banner",
        "title": "Custom Hand Painted Birthday Banner",
        "price": 100,
        "category": "birthday",
        "image": "custom-hand-painted-birthday-banner",
        "orientation": "landscape",
        "wording": "Happy Birthday Gabbie",
        "alt": "Hand-painted birthday banner on kraft paper reading Happy Birthday Gabbie with sunflowers, a basketball, iced coffee, shamrocks and a dachshund",
        "blurb": "A hobby-packed birthday banner: white script lettering over kraft paper, the name in warm rust, and a border of everything Gabbie loves.",
        "details": ["Hand-lettered white script with the name in rust orange", "Sunflowers, shamrocks and a basketball", "Iced coffee, a hot latte and a little dachshund", "Painted on kraft paper, ready to tape or clip to the wall"],
        "palette": ["#C9A574", "#F5F0E6", "#C0552B", "#E8A838", "#5F8F3E"],
        "published": "2026-03-27",
    },
    {
        "slug": "custom-hand-painted-birthday-banner-2",
        "title": "Custom Hand Painted Birthday Banner #2",
        "price": 90,
        "category": "birthday",
        "image": "custom-hand-painted-birthday-banner-2",
        "orientation": "landscape",
        "wording": "Everly is two",
        "alt": "Hand-painted second birthday banner with a pink gingham border, ladybugs, daisies and bows reading Everly is two",
        "blurb": "Pink gingham, ladybugs and daisies frame a scalloped white panel for a second birthday that is sweet without being fussy.",
        "details": ["Pink gingham border painted by hand", "Scalloped white frame with soft yellow script", "Ladybugs, daisies and pink bows in every corner", "Sized to hang behind a cake table"],
        "palette": ["#C9A574", "#F4B6C2", "#FFFFFF", "#C8102E", "#F2D16B"],
        "published": "2026-03-30",
    },
    {
        "slug": "hand-painted-over-then-moon-banner",
        "title": "Hand Painted Over Then Moon Banner",
        "price": 100,
        "category": "baby",
        "image": "hand-painted-over-then-moon-banner",
        "orientation": "landscape",
        "wording": "Over the Moon for Baby Boy Orion",
        "alt": "Hand-painted baby shower banner reading Over the Moon for Baby Boy Orion surrounded by planets, stars and shooting stars",
        "blurb": "A space-themed baby shower banner with Saturn, Jupiter, Earth, the moon and a sky full of shooting stars around bright blue script.",
        "details": ["Blue script name with bold navy headline", "Saturn, Jupiter, Mars, Earth and the moon", "Shooting stars and sparkles scattered to the edges", "Painted on kraft paper for a warm, galaxy-nursery feel"],
        "palette": ["#C9A574", "#2E5AAC", "#F2C94C", "#E8743B", "#FFFFFF"],
        "published": "2026-03-30",
    },
    {
        "slug": "childrens-church-hand-painted-banner",
        "title": "Children's Church Hand Painted Banner",
        "price": 100,
        "category": "church",
        "image": "childrens-church-hand-painted-banner",
        "orientation": "portrait",
        "wording": "Children's Church - Rejoice for He Is Risen (Matthew 28:6)",
        "alt": "Tall hand-painted Easter banner for children's church reading Rejoice for He Is Risen with a cross, the empty tomb, butterflies and spring flowers",
        "blurb": "An Easter banner for children's church: the empty tomb, a draped cross, butterflies and a bed of spring wildflowers under bold gold-and-white lettering.",
        "details": ["Matthew 28:6 painted in full beneath the headline", "Draped cross and empty tomb scene", "Purple butterflies and spring wildflowers", "Portrait format for a classroom wall or stage"],
        "palette": ["#C9A574", "#F2C94C", "#FFFFFF", "#8A64A7", "#5F8F3E"],
        "published": "2026-03-30",
    },
    {
        "slug": "custom-hand-painted-birthday-banner-3",
        "title": "Custom Hand Painted Birthday Banner #3",
        "price": 100,
        "category": "birthday",
        "image": "custom-hand-painted-birthday-banner-3",
        "orientation": "landscape",
        "wording": "Happy Birthday Amber",
        "alt": "Hand-painted birthday banner reading Happy Birthday Amber with a painted cowgirl portrait and a coffee cup",
        "blurb": "Block lettering in teal and cream, a painted cowgirl portrait and a coffee cup with a heart. Simple, personal and very Texas.",
        "details": ["Cream block capitals with the name in teal", "Hand-painted cowgirl portrait with hat and fringe", "Coffee cup with a heart", "Landscape format, easy to hang above a table"],
        "palette": ["#C9A574", "#1A8084", "#F5F0E6", "#6B4A2B", "#2F2F2F"],
        "published": "2026-03-30",
    },
    {
        "slug": "custom-hand-painted-birthday-banner-4",
        "title": "Custom Hand Painted Birthday Banner #4",
        "price": 100,
        "category": "birthday",
        "image": "custom-hand-painted-birthday-banner-4",
        "orientation": "landscape",
        "wording": "Jeremiah turning 5",
        "alt": "Hand-painted construction-themed fifth birthday banner reading Jeremiah turning 5 with a road-marking number five and a yellow tractor",
        "blurb": "A construction-site fifth birthday: chunky white lettering, a number five painted like a road with lane markings, and a cheerful yellow tractor.",
        "details": ["Bold white lettering with a wavy cream border", "Number 5 painted as a road with dashed lines", "Yellow front-loader tractor", "Great backdrop for a dig-site party"],
        "palette": ["#C9A574", "#FFFFFF", "#2F2F2F", "#F2C94C", "#2E5AAC"],
        "published": "2026-03-30",
    },
    {
        "slug": "custom-painted-verse-banner",
        "title": "Custom Painted Verse Banner",
        "price": 100,
        "category": "scripture",
        "image": "custom-painted-verse-banner",
        "orientation": "landscape",
        "wording": "Love the Lord your God with all your heart & all your soul & all your mind & all your strength - Mark 12:30",
        "alt": "Hand-painted scripture banner of Mark 12:30 in red script with pink, purple and white hearts",
        "blurb": "Mark 12:30 lettered in deep red script with a scatter of pink, lavender and white hearts. A verse banner for a classroom, a Valentine's lesson or a living room.",
        "details": ["Full verse hand-lettered in red script", "Hearts in pink, lavender, white and purple", "Clean kraft background keeps the words readable", "Landscape format"],
        "palette": ["#C9A574", "#B4232C", "#F4B6C2", "#8A64A7", "#FFFFFF"],
        "published": "2026-03-30",
    },
    {
        "slug": "childrens-church-hand-painted-banner-2",
        "title": "Children's Church Hand Painted Banner #2",
        "price": 100,
        "category": "church",
        "image": "childrens-church-hand-painted-banner-2",
        "orientation": "portrait",
        "wording": "Children's Church - God's Love Letters to You!",
        "alt": "Tall hand-painted children's church banner reading God's Love Letters to You with a heart garland, a red mailbox and painted envelopes carrying Bible verses",
        "blurb": "A Valentine's lesson banner: a heart garland, a red mailbox and a wall of painted envelopes, each carrying a verse about God's love.",
        "details": ["Headline in white with a hand-strung heart garland", "Red mailbox and a dozen painted envelopes", "Verses from Romans, 1 John, 1 Peter and more", "Portrait format for a stage or classroom door"],
        "palette": ["#C9A574", "#FFFFFF", "#B4232C", "#F4B6C2", "#8A64A7"],
        "published": "2026-03-30",
    },
    {
        "slug": "custom-painted-verse-banner-2",
        "title": "Custom Painted Verse Banner #2",
        "price": 100,
        "category": "scripture",
        "image": "custom-painted-verse-banner-2",
        "orientation": "landscape",
        "wording": "For unto you is born this day in the city of David a Savior, which is Christ the Lord - Luke 2:11",
        "alt": "Hand-painted Christmas scripture banner of Luke 2:11 with a nativity silhouette and pine branches with red berries",
        "blurb": "Luke 2:11 above a nativity silhouette with the star shining down, framed by pine branches and red berries. A Christmas banner that works for church or home.",
        "details": ["Verse in black with key words in white script", "Nativity scene painted in silhouette", "Pine branches and red berries down both sides", "Landscape format"],
        "palette": ["#C9A574", "#2F2F2F", "#FFFFFF", "#5F8F3E", "#B4232C"],
        "published": "2026-03-30",
    },
    {
        "slug": "custom-painted-fall-banner",
        "title": "Custom Painted Fall Banner",
        "price": 100,
        "category": "seasonal",
        "image": "custom-painted-fall-banner",
        "orientation": "landscape",
        "wording": "Happy Fall!",
        "alt": "Hand-painted Happy Fall banner on grey paper with a pumpkin, acorn, autumn leaves and a cross",
        "blurb": "Soft blue script on grey paper with a pumpkin, an acorn, falling leaves and a small cross. A seasonal banner for a porch, a classroom or a fall festival table.",
        "details": ["Pale blue script lettering", "Pumpkin, acorn and autumn leaves in the corners", "Small painted cross", "Painted on grey paper for a softer look"],
        "palette": ["#9A9A9A", "#A9C7E8", "#E8743B", "#B4232C", "#6B4A2B"],
        "published": "2026-03-30",
    },
    {
        "slug": "custom-painted-verse-banner-3",
        "title": "Custom Painted Verse Banner #3",
        "price": 100,
        "category": "scripture",
        "image": "custom-painted-verse-banner-3",
        "orientation": "landscape",
        "wording": "A child has been born for us... and he is named Jesus - Isaiah 9:6 (CHRISTMAS acrostic)",
        "alt": "Hand-painted Isaiah 9:6 Christmas banner with the word CHRISTMAS running down the verse as a gold acrostic, framed by holly and berries",
        "blurb": "Isaiah 9:6 with the letters of CHRISTMAS picked out in gold down the middle of the verse, a manger and a holly-and-berry border.",
        "details": ["Acrostic lettering: CHRISTMAS in gold through the verse", "Manger with a small cross", "Holly leaves and red berries around the edge", "Landscape format"],
        "palette": ["#C9A574", "#2F2F2F", "#F2C94C", "#5F8F3E", "#B4232C"],
        "published": "2026-03-31",
    },
    {
        "slug": "custom-hand-painted-banner",
        "title": "Custom Hand Painted Banner",
        "price": 100,
        "category": "birthday",
        "image": "custom-hand-painted-banner",
        "orientation": "portrait",
        "wording": "21 (clinking cans)",
        "alt": "Close-up of a hand-painted 21st birthday banner detail showing two clinking Lite cans with the number 21 against green camo",
        "blurb": "A detail from a 21st birthday banner: two clinking cans painted can-by-can, label and all, against a green camo background.",
        "details": ["Painted cans with lettering, foam and the number 21", "Camouflage pattern painted in layered greens", "Shows the level of detail possible on a custom banner", "Pairs with the Happy 21st Birthday Gabe banner"],
        "palette": ["#C9A574", "#FFFFFF", "#2E5AAC", "#5F8F3E", "#2F2F2F"],
        "published": "2026-03-31",
    },
    {
        "slug": "custom-hand-painted-birthday-banner-5",
        "title": "Custom Hand Painted Birthday Banner #5",
        "price": 100,
        "category": "birthday",
        "image": "custom-hand-painted-birthday-banner-5",
        "orientation": "landscape",
        "wording": "Happy 21st Birthday Gabe",
        "alt": "Hand-painted 21st birthday banner reading Happy 21st Birthday Gabe with a camo border, cowboy hat, boots and clinking cans",
        "blurb": "A western 21st: camo border, a badge-shaped frame around the greeting, a cowboy hat, boots and a pair of clinking cans in the corner.",
        "details": ["Badge-style frame with the name in green", "Camouflage border painted by hand", "Cowboy hat, boots and clinking cans", "Landscape format"],
        "palette": ["#C9A574", "#5F8F3E", "#6B4A2B", "#FFFFFF", "#2F2F2F"],
        "published": "2026-03-31",
    },
    {
        "slug": "custom-painted-verse-banner-4",
        "title": "Custom Painted Verse Banner #4",
        "price": 100,
        "category": "church",
        "image": "custom-painted-verse-banner-4",
        "orientation": "portrait",
        "wording": "Children's Church - With all my heart I will thank the Lord - Psalms 111:1",
        "alt": "Tall hand-painted Thanksgiving children's church banner of Psalm 111:1 with a rope frame, a cowboy praying at a cross with his horse, a cornucopia and a wagon wheel",
        "blurb": "A Thanksgiving banner for children's church: Psalm 111:1 inside a rope frame, a cowboy kneeling at a cross with his horse, a cornucopia and a wagon wheel.",
        "details": ["Rope frame around the verse", "Praying cowboy, horse and cross", "Cornucopia with pumpkins and harvest", "Portrait format"],
        "palette": ["#C9A574", "#FFFFFF", "#2F2F2F", "#E8743B", "#6B4A2B"],
        "published": "2026-03-31",
    },
    {
        "slug": "custom-painted-verse-banner-5",
        "title": "Custom Painted Verse Banner #5",
        "price": 100,
        "category": "seasonal",
        "image": "custom-painted-verse-banner-5",
        "orientation": "landscape",
        "wording": "Seasons change but Jesus Christ remains the same - Hebrews 13:8",
        "alt": "Hand-painted fall scripture banner of Hebrews 13:8 with a rope frame, sunflowers, a pumpkin, a cowboy hat, a boot, a horseshoe and hot cocoa",
        "blurb": "Hebrews 13:8 in a rope frame with sunflowers, a pumpkin, a boot, a horseshoe, a cowboy hat and a mug of cocoa. Fall, faith and a little Texas.",
        "details": ["Verse in black with Jesus Christ in bold script", "Rope frame with sunflowers across the bottom", "Pumpkin, horseshoe, boot, hat and cocoa", "Landscape format"],
        "palette": ["#C9A574", "#2F2F2F", "#F2C94C", "#E8743B", "#6B4A2B"],
        "published": "2026-03-31",
    },
    {
        "slug": "custom-hand-painted-birthday-banner-6",
        "title": "Custom Hand Painted Birthday Banner #6",
        "price": 100,
        "category": "birthday",
        "image": "custom-hand-painted-birthday-banner-6",
        "orientation": "landscape",
        "wording": "Happy Birthday Ashlee",
        "alt": "Hand-painted birthday banner reading Happy Birthday Ashlee in pink script with a highland cow, a capybara in a party hat, pink bows and a cola can",
        "blurb": "White block capitals, the name in pink script, a highland cow with a bow, a capybara in a party hat and a cola can. Playful and personal.",
        "details": ["White capitals with the name in pink script", "Highland cow and capybara with party hats", "Pink bows and a painted cola can", "Landscape format"],
        "palette": ["#C9A574", "#FFFFFF", "#F4B6C2", "#B4232C", "#6B4A2B"],
        "published": "2026-03-31",
    },
    {
        "slug": "custom-hand-painted-birthday-banner-7",
        "title": "Custom Hand Painted Birthday Banner #7",
        "price": 100,
        "category": "birthday",
        "image": "custom-hand-painted-birthday-banner-7",
        "orientation": "landscape",
        "wording": "Happy Birthday Gabbie",
        "alt": "Finished hand-painted Happy Birthday Gabbie banner hung on a wall with sunflowers, a basketball, coffee cups and shamrocks",
        "blurb": "The finished Happy Birthday Gabbie banner, hung and ready for the party. Sunflowers, coffee, a basketball and a dachshund around warm script lettering.",
        "details": ["Shown hung on the wall at full size", "Sunflowers, basketball, shamrocks and coffee", "Rust-orange name on white script", "Landscape format"],
        "palette": ["#C9A574", "#F5F0E6", "#C0552B", "#E8A838", "#5F8F3E"],
        "published": "2026-03-31",
    },
]

BY_SLUG = {c["slug"]: c for c in CREATIONS}
CATEGORY_LABEL = dict(CATEGORIES)


def by_category(cat):
    return [c for c in CREATIONS if c["category"] == cat]
