"""Service page content. Each entry renders /services/<slug>/."""

SERVICES = [
    {
        "slug": "wind-hail",
        "name": "Wind & hail damage",
        "short": "Wind & hail",
        "icon": "hail",
        "img": "roof-inspection",
        "img2": "hail-roof",
        "img_alt": "Inspector standing on a storm-damaged shingle roof of a brick home",
        "img2_alt": "Hailstones on a lawn after a North Texas hailstorm",
        "title": "Hail & Wind Damage Claims | The Colony Public Adjuster",
        "desc": "Hail or wind damage in The Colony, TX? The Colony Public Adjuster documents roof, siding, window and fence damage and presents a supported storm claim.",
        "h1": "Hail and wind damage claims, <em>documented in full.</em>",
        "lead": "North Texas storms move fast. The damage they leave on roofs, gutters, siding, windows and fences can take far longer to sort out. The Colony Public Adjuster helps you build a complete, well-supported storm claim.",
        "card": "Roofing, siding, windows, gutters, fencing and storm-driven interior leaks.",
        "intro_h": "Look beyond the most obvious storm damage.",
        "intro": [
            "The Colony sits in one of the most hail-prone corridors in the country. Spring supercells that track across Denton County can drop hail on one street and spare the next, and straight-line winds off Lewisville Lake can lift shingles, bend flashing and drop limbs onto roofs and fences.",
            "Storm damage is rarely limited to the roof. Soft metals such as gutters, downspouts, vents and AC fins often show the clearest evidence of hail size and direction. Water that enters through a damaged roof can stain ceilings weeks later. As your public adjuster in The Colony, we review the reported loss as a whole and document related exterior and interior conditions without assuming every issue came from the same event.",
        ],
        "organize": [
            "Roof covering, ridge, flashing, vents and other rooftop components",
            "Gutters, downspouts, window screens, siding and garage doors",
            "Fencing, sheds, pergolas and other structures on the property",
            "Interior ceilings and walls affected by storm-related water entry",
            "Measurements, photo logs and Xactimate-format repair scopes",
            "Storm date research, contractor findings and carrier estimates",
        ],
        "disputes_h": "Where storm claims often stall",
        "disputes": [
            ("Repair vs. replacement", "A carrier estimate may approve a few shingles where the roof's condition, brittleness or matching issues call for a broader scope. We document the reasons behind the scope you are asking for."),
            ("Cosmetic vs. functional", "Some policies limit cosmetic damage to metal roofing or siding. We read the endorsement and document what the damage actually does to the component."),
            ("Wear and tear vs. storm", "Age is not a reason to ignore new damage. We separate pre-existing wear from fresh impact marks with photographs and measurements."),
            ("Missed elevations", "Damage on one slope or one side of the house is easy to overlook. We inspect every elevation and every exterior component."),
        ],
        "first_h": "What to do after a storm in The Colony",
        "first": "Photograph visible damage from the ground or a safe window. Do not climb a damaged roof. Write down the approximate time of the storm and when you first noticed each problem, cover openings to prevent further damage, and keep every receipt for temporary repairs such as tarps or board-up.",
        "faqs": [
            ("How long do I have to file a hail claim in Texas?", "Your policy sets the notice requirements, and many Texas homeowner policies require prompt notice. Check your policy and report damage as soon as you discover it. A public adjuster can help after the claim is filed, but do not delay notice while waiting for a review."),
            ("Will a hail claim raise my premium?", "Rates depend on your insurer, your claims history and how the carrier rates weather events. We cannot predict pricing decisions. Many homeowners ask their agent this question before filing."),
            ("What if the insurer says the damage is just wear and tear?", "Ask for the explanation in writing. Then compare it with dated photographs, the storm date and an independent inspection. The Colony Public Adjuster can review whether the evidence supports a storm-caused loss."),
        ],
        "blog": ["after-a-hailstorm-the-colony", "reading-property-claim-estimate"],
    },
    {
        "slug": "water-damage",
        "name": "Water damage",
        "short": "Water damage",
        "icon": "droplet",
        "img": "water-damage",
        "img2": "inventory",
        "img_alt": "Water-damaged ceiling with plaster torn away after a leak",
        "img2_alt": "Living room interior representing rooms affected by a water loss",
        "title": "Water Damage Insurance Claims | The Colony Public Adjuster",
        "desc": "Burst pipe, slab leak or appliance failure? The Colony Public Adjuster helps homeowners in The Colony, TX document water damage and present a clear claim.",
        "h1": "Water damage claims that tell <em>the whole story.</em>",
        "lead": "Plumbing failures, appliance leaks, burst pipes and storm-driven water can spread farther than you can see. The Colony Public Adjuster helps you document the source, the spread and the work needed to put things right.",
        "card": "Burst pipes, slab and supply-line leaks, appliance failures and mitigation disputes.",
        "intro_h": "Follow the water, room by room.",
        "intro": [
            "With water losses, the cause and the timing matter as much as the damage itself. A sudden supply-line break, a slow leak behind a wall, wind-driven rain and rising floodwater can each raise different policy questions. Many North Texas homes are built on slab foundations, so plumbing leaks can travel under flooring before anyone notices.",
            "Hard freezes, such as February 2021's Winter Storm Uri, showed how quickly burst pipes can affect several rooms at once. The Colony Public Adjuster organizes the record for the reported event: where the water came from, what it reached, what was done to dry the structure, and what still needs repair.",
        ],
        "organize": [
            "The reported source and a clear discovery timeline",
            "Plumber or leak-detection findings and repair invoices",
            "Moisture readings, drying logs and mitigation invoices",
            "Affected flooring, drywall, cabinetry, trim and contents",
            "Room-by-room photos before, during and after mitigation",
            "Additional living expense records if the home is unlivable",
        ],
        "disputes_h": "Common questions in water claims",
        "disputes": [
            ("Sudden vs. continuous", "Policies often treat a sudden accidental discharge differently from long-term seepage. Clear dates and a professional cause assessment help answer this question."),
            ("Tear-out and access", "Reaching a leak under a slab or inside a wall may require removing finishes. We document why access was needed and what it affected."),
            ("Mitigation invoices", "Drying invoices are sometimes reduced. We gather the moisture logs and equipment records that explain the work performed."),
            ("Matching and continuity", "Flooring that runs through several rooms can raise matching questions. We record layout, material and availability."),
        ],
        "first_h": "First steps after a water leak",
        "first": "If it is safe, shut off the water and electricity to affected areas, and call a plumber or mitigation company. Photograph the water before cleanup begins, keep the plumber's written findings, and save every invoice. Note where furniture and contents were before anything was moved.",
        "faqs": [
            ("Does homeowners insurance cover a slab leak in Texas?", "It depends on your policy language. Some policies cover resulting damage and the cost to access the leak but not the pipe repair itself. We review the coverage language that applies to your loss."),
            ("Should I start drying before the adjuster arrives?", "Generally, yes. Most policies expect you to take reasonable steps to prevent further damage. Document conditions first, then keep records of the mitigation work."),
            ("Is flood damage covered by my homeowners policy?", "Rising surface water is usually excluded from standard homeowner policies and covered under separate flood insurance. Water released from plumbing is a different question. We help you sort out which applies."),
        ],
        "blog": ["water-damage-documentation", "home-inventory-before-loss"],
    },
    {
        "slug": "fire-smoke",
        "name": "Fire & smoke damage",
        "short": "Fire & smoke",
        "icon": "flame",
        "img": "fire-smoke",
        "img2": "inspector",
        "img_alt": "Fire-damaged house structure after a residential fire",
        "img2_alt": "Claim professional reviewing damage details with homeowners",
        "title": "Fire & Smoke Damage Claims | The Colony Public Adjuster",
        "desc": "After a fire, The Colony Public Adjuster documents structural damage, smoke and soot, contents and living expenses so your claim reflects the full loss.",
        "h1": "A careful record of <em>what the fire left behind.</em>",
        "lead": "A fire claim can touch every part of your property and your daily life: the structure, smoke and soot residue, personal belongings, and where you will live during repairs. The Colony Public Adjuster brings order to all of it.",
        "card": "Structure, smoke and soot residue, contents and additional living expenses.",
        "intro_h": "Document what can be seen and what needs testing.",
        "intro": [
            "Fire damage is usually obvious near the source. Smoke and soot travel much farther, through HVAC systems, attics, wall cavities and closed rooms. Odor, residue and heat exposure can affect materials and belongings that look fine at first glance.",
            "Once the property is safe to enter, The Colony Public Adjuster helps you gather and organize the information that supports your fire claim: structural damage, cleaning and restoration needs, a detailed contents inventory, and the additional living expenses that follow when you cannot stay in your home.",
        ],
        "organize": [
            "Structural damage and affected building systems",
            "Smoke, soot and odor assessment and cleaning scopes",
            "Room-by-room contents lists with photos and receipts",
            "Board-up, debris removal and emergency service invoices",
            "Additional living expense (ALE) receipts and records",
            "Fire department and investigation report references",
        ],
        "disputes_h": "Where fire claims get complicated",
        "disputes": [
            ("Clean vs. replace", "Cleaning is not always enough for porous materials and electronics. We document what has been tried and why replacement may be needed."),
            ("Contents valuation", "Large contents lists are hard to build from memory. We help organize them by room with ages, quantities and replacement costs."),
            ("Additional living expenses", "Temporary housing, extra mileage and meals can add up. We keep ALE receipts organized and tied to the loss."),
            ("Hidden smoke spread", "Smoke in the HVAC system or attic can be missed. We look for it and document the areas affected."),
        ],
        "first_h": "First steps after a house fire",
        "first": "Wait for clearance from the fire department before entering. Secure the property, keep every receipt for temporary housing and emergency purchases, and start a contents list from memory while you are away. Earlier family photos and online order histories can help rebuild the list.",
        "faqs": [
            ("Does insurance cover smoke damage without flames in my home?", "Many policies cover smoke damage from a covered fire, including fires nearby. Coverage depends on your policy and the source. We help document the smoke impact either way."),
            ("What are additional living expenses?", "ALE, also called loss of use, can cover the increase in living costs while your home is being repaired, subject to your policy limits and terms. Keep every receipt."),
            ("How detailed does my contents inventory need to be?", "Detailed enough that someone else could identify each item and its approximate age and value. Our free home inventory tool can help you build it room by room."),
        ],
        "blog": ["home-inventory-before-loss", "reading-property-claim-estimate"],
    },
    {
        "slug": "residential",
        "name": "Residential property",
        "short": "Residential",
        "icon": "home",
        "img": "residential",
        "img2": "inventory",
        "img_alt": "Brick single-story home with a front lawn in North Texas",
        "img2_alt": "Bright living room in a family home",
        "title": "Residential Public Adjuster in The Colony, TX",
        "desc": "Homeowner claim help from The Colony Public Adjuster: building, other structures, contents and living expenses, documented and presented on your behalf.",
        "h1": "A home is personal. <em>Your claim should be too.</em>",
        "lead": "Homes, townhomes, rental houses and everything inside them. The Colony Public Adjuster represents homeowners and landlords in The Colony through the full property claim.",
        "card": "Homes, townhomes, rentals and the belongings that make them yours.",
        "intro_h": "Your home, viewed as a whole.",
        "intro": [
            "A homeowner claim can involve the dwelling, detached structures such as fences and sheds, personal property, and additional living expenses. Each part of the policy has its own limits, deductibles and conditions, and the evidence needed for each is different.",
            "From a newer build in Austin Ranch to an established home near Stewart Creek Park, The Colony Public Adjuster starts with the facts of your property. We organize the damage record, compare estimates line by line and help you understand which questions to raise under your specific policy.",
        ],
        "organize": [
            "Room-by-room photographs and damage notes",
            "Dwelling and other-structures repair scopes",
            "Personal property (contents) inventories",
            "Carrier estimates compared with contractor scopes",
            "Receipts for temporary repairs and living expenses",
            "Policy declarations, endorsements and correspondence",
        ],
        "disputes_h": "What homeowners often ask us to review",
        "disputes": [
            ("A low estimate", "Line items, quantities or labor may be missing. We compare scopes side by side and document the gaps."),
            ("Depreciation", "Withheld depreciation and how to recover it can be confusing. We explain the numbers and the steps involved."),
            ("Code upgrades", "Repairs may require work to meet current building codes. We look at whether your policy includes ordinance or law coverage."),
            ("Slow progress", "When a claim stalls, an organized file and clear follow-up can help move it forward."),
        ],
        "first_h": "Where to start",
        "first": "Make a simple room list. Keep photos and receipts in folders named for each room, and record when the damage was first discovered. Gather your declarations page and any letters or estimates from the insurer.",
        "faqs": [
            ("Can a public adjuster help with a rental property I own?", "Yes. Landlords and owners of single-family rentals can be represented for damage to the building and their own property. Tenants' belongings fall under the tenant's own policy."),
            ("Do I need a public adjuster for a small claim?", "Not always. For a straightforward loss you may be comfortable handling it yourself. We will tell you honestly during the free review if representation is unlikely to help."),
            ("Can you help after I already received a payment?", "Often, yes. Depending on your policy and timelines, a supplemental claim or a request for reconsideration may be possible. Bring the estimate and payment letter to the review."),
        ],
        "blog": ["reading-property-claim-estimate", "home-inventory-before-loss"],
    },
    {
        "slug": "commercial",
        "name": "Commercial property",
        "short": "Commercial",
        "icon": "building",
        "img": "commercial",
        "img2": "consultation",
        "img_alt": "Modern commercial office building at dusk",
        "img2_alt": "Business owner meeting with a claim professional",
        "title": "Commercial Public Adjuster in The Colony, TX",
        "desc": "The Colony Public Adjuster helps business owners and property managers with commercial property, storm, water, fire and business interruption claims.",
        "h1": "Keep your focus on <em>getting back to business.</em>",
        "lead": "Retail centers, offices, restaurants, warehouses, churches and multifamily buildings. The Colony Public Adjuster organizes complex commercial losses so owners and managers can keep operating.",
        "card": "Offices, retail, restaurants, warehouses, multifamily and business income.",
        "intro_h": "Bring a complex property file into focus.",
        "intro": [
            "Commercial losses involve more stakeholders, more records and more policy parts: building, business personal property, tenant improvements, equipment, and business income or extra expense. Large flat roofs and rooftop units are especially exposed during North Texas hail events.",
            "From the shops and offices along the SH 121 corridor and Grandscape to light-industrial space and multifamily properties, The Colony Public Adjuster helps owners and property managers build an organized, well-supported claim while they focus on tenants, customers and operations.",
        ],
        "organize": [
            "Roofing systems, rooftop HVAC units and building envelope",
            "Building components, fixtures and tenant improvements",
            "Inventory, equipment and business personal property records",
            "Business income and extra expense documentation",
            "Contractor bids, engineering reports and repair scopes",
            "Lease obligations, access logs and inspection timelines",
        ],
        "disputes_h": "Where commercial claims get complex",
        "disputes": [
            ("Large-loss scopes", "Commercial roofs and building systems need detailed measurements and specialized pricing. We prepare scopes that reflect the actual system."),
            ("Business income", "Lost income calculations depend on records and timelines. We help organize the financial documentation the policy calls for."),
            ("Coinsurance", "Underinsurance penalties can reduce a payment. We review limits and values early so there are no surprises."),
            ("Multiple stakeholders", "Owners, tenants, lenders and managers all need updates. A single organized file keeps everyone aligned."),
        ],
        "first_h": "A useful first step for businesses",
        "first": "Name one contact for the property, one for financial records and one for repair coordination. Keep a shared timeline of access, inspections and changes to the premises, and preserve damaged inventory or equipment until it has been documented.",
        "faqs": [
            ("Do you handle HOA and multifamily claims?", "Yes. We work with associations, owners and property managers on common-area and building damage, subject to the policy and governing documents."),
            ("Can you help with a business interruption claim?", "We help organize documentation for business income and extra expense where the policy includes it, working alongside your accountant when needed."),
            ("How do you work with our contractor?", "We coordinate scopes and documentation with your chosen contractor. We do not perform repairs ourselves, and you keep control over who does the work."),
        ],
        "blog": ["denied-underpaid-claim-review", "reading-property-claim-estimate"],
    },
    {
        "slug": "denied-underpaid",
        "name": "Denied & underpaid claims",
        "short": "Denied & underpaid",
        "icon": "filex",
        "img": "denied-claim",
        "img2": "estimate",
        "img_alt": "Insurance claim paperwork and decision letters on a desk",
        "img2_alt": "Reviewing an insurance estimate with a calculator",
        "title": "Denied or Underpaid Claim Help | The Colony Public Adjuster",
        "desc": "Insurance claim denied, delayed or underpaid? The Colony Public Adjuster reviews the decision, estimate and evidence and helps you pursue a supported next step.",
        "h1": "A disappointing decision deserves <em>a second look.</em>",
        "lead": "A denial letter, a low estimate or a claim that has gone quiet is not always the final word. The Colony Public Adjuster takes a fresh look at the decision, the policy and the evidence.",
        "card": "Fresh eyes on denial letters, low estimates, delays and missed damage.",
        "intro_h": "Start with the reason behind the decision.",
        "intro": [
            "Every denial or partial payment should come with a written explanation. Reading it closely is the first step. A coverage question, such as whether an exclusion applies, needs different evidence than a disagreement about the scope or cost of repairs.",
            "The Colony Public Adjuster compares the decision with your policy, the carrier's estimate and the supporting evidence to identify questions that may deserve further review. When the facts support it, we prepare a supplemental claim or request reconsideration and handle the follow-up with the carrier.",
        ],
        "organize": [
            "The written decision and every cited policy provision",
            "Each version of the carrier estimate and payment letters",
            "Contractor scopes and independent inspection findings",
            "Photos, reports and correspondence already submitted",
            "A line-by-line list of disputed or omitted items",
            "Supporting documentation for each item under review",
        ],
        "disputes_h": "Common reasons claims are denied or underpaid",
        "disputes": [
            ("Missed damage", "Elevations, rooms or components that were never inspected. A thorough re-inspection can show what was left out."),
            ("Pricing and quantities", "Measurements, waste factors or labor that do not match the actual repair. We compare the scopes line by line."),
            ("Cause of loss", "Disputes over whether a storm, a leak or wear caused the damage. We gather the evidence that speaks to cause."),
            ("Missing documents", "Claims stall when requested items never reach the reviewer. We index what was sent and when."),
        ],
        "first_h": "Before you respond to the insurer",
        "first": "Keep the entire decision letter and every estimate version. List the specific items you believe are missing or undervalued, along with the records that support each one. Note any deadlines in the letter or your policy. Legal questions or releases may call for an attorney.",
        "faqs": [
            ("Can I reopen a claim after it was closed?", "Sometimes. Many claims can be supplemented when new damage or additional costs are documented, subject to policy terms and deadlines. Bring the closing letter to your review."),
            ("What is the appraisal clause?", "Many Texas property policies include an appraisal process for disputes about the amount of loss. It has specific steps and costs. We can explain how it works under your policy."),
            ("Will a public adjuster guarantee a higher payment?", "No one can guarantee a result. Our role is to document and present what the evidence and your policy support, and to tell you honestly what we find."),
        ],
        "blog": ["denied-underpaid-claim-review", "reading-property-claim-estimate"],
    },
]

SERVICE_BY_SLUG = {s["slug"]: s for s in SERVICES}
