<?php
// stonecoatedroofs.com - static site front controller.
// The host serves existing files directly and routes "/" and unknown paths here.
$path = strtok($_SERVER['REQUEST_URI'] ?? '/', '?');
$home = 'https://stonecoatedroofs.com';
$host = $_SERVER['HTTP_HOST'] ?? '';

// Canonical scheme/host (TLS terminates upstream, so trust X-Forwarded-Proto).
$insecure = ($_SERVER['HTTP_X_FORWARDED_PROTO'] ?? '') === 'http';
if ($host === 'www.stonecoatedroofs.com' || ($insecure && $host === 'stonecoatedroofs.com')) {
    header('Location: ' . $home . ($_SERVER['REQUEST_URI'] ?? '/'), true, 301);
    exit;
}

if ($path === '/' || $path === '/index.php') {
    header('Content-Type: text/html; charset=utf-8');
    readfile(__DIR__ . '/home.html');
    exit;
}

// Dead links the old WordPress posts pointed at (map generated by build.py).
$map = @include __DIR__ . '/redirects.php';
$key = rtrim($path, '/') . '/';
if (is_array($map) && isset($map[$key])) {
    header('Location: ' . $home . $map[$key], true, 301);
    exit;
}
// /blog/<post>/ -> /<post>/ (posts live at the root)
if (preg_match('#^/blog/([a-z0-9-]+)/?$#', $path, $m) && $m[1] !== 'page' && is_dir(__DIR__ . '/' . $m[1])) {
    header('Location: ' . $home . '/' . $m[1] . '/', true, 301);
    exit;
}

// Old WordPress URLs with no static equivalent -> nearest page.
$redirects = [
    '#^/(feed|comments/feed|blog/feed)/?$#'                         => '/blog/',
    '#^/topic/([a-z0-9-]+)/feed/?$#'                                => '/topic/$1/',
    '#^/topic/([a-z0-9-]+)/page/\d+/?$#'                            => '/topic/$1/',
    '#^/(author|tag)/.*$#'                                          => '/blog/',
    '#^/(wp-admin|wp-includes|wp-json|wp-login\.php|xmlrpc\.php)(/|$)#' => '/',
    '#^/([a-z0-9-]+)/(feed|amp|embed)/?$#'                          => '/$1/',
];
foreach ($redirects as $re => $to) {
    if (preg_match($re, $path)) {
        header('Location: ' . $home . preg_replace($re, $to, $path), true, 301);
        exit;
    }
}
if (preg_match('#^/blog/page/(\d+)/?$#', $path, $m) && !is_dir(__DIR__ . "/blog/page/{$m[1]}")) {
    header('Location: ' . $home . '/blog/', true, 301);
    exit;
}
if ($path === '/wp-sitemap.xml') {
    header('Location: ' . $home . '/sitemap_index.xml', true, 301);
    exit;
}
// Directory without trailing slash -> add it.
if (substr($path, -1) !== '/' && strpos($path, '..') === false && is_dir(__DIR__ . $path)) {
    header('Location: ' . $home . $path . '/', true, 301);
    exit;
}
http_response_code(404);
header('Content-Type: text/html; charset=utf-8');
readfile(__DIR__ . '/404.html');
