<?php
// rooftarp.com - static site front controller. See README, "Hosting note".
// Generated by build.py - do not edit by hand.
$path = strtok($_SERVER['REQUEST_URI'] ?? '/', '?');
$home = 'https://rooftarp.com';

// Canonical host and scheme. TLS terminates upstream, so REQUEST_SCHEME is
// always http here; X-Forwarded-Proto carries the real scheme.
$insecure = ($_SERVER['HTTP_X_FORWARDED_PROTO'] ?? '') === 'http';
if ($insecure || ($_SERVER['HTTP_HOST'] ?? '') === 'www.rooftarp.com') {
    header('Location: ' . $home . ($_SERVER['REQUEST_URI'] ?? '/'), true, 301);
    exit;
}

if ($path === '/' || $path === '/index.php') {
    header('Content-Type: text/html; charset=utf-8');
    readfile(__DIR__ . '/home.html');
    exit;
}

// 141 removed near-duplicate city pages -> 410 Gone. These earned zero
// clicks in 16 months and were 96-98% identical to one another; 410 tells
// Google they are intentionally gone. Kept city pages exist as real files
// and never reach this controller.
$gone = [
    'roof-tarp-abilene',
    'roof-tarp-allen',
    'roof-tarp-alton',
    'roof-tarp-alvin',
    'roof-tarp-amarillo',
    'roof-tarp-anna',
    'roof-tarp-atascocita',
    'roof-tarp-balch-springs',
    'roof-tarp-bastrop',
    'roof-tarp-baytown',
    'roof-tarp-bedford',
    'roof-tarp-belton',
    'roof-tarp-benbrook',
    'roof-tarp-big-spring',
    'roof-tarp-boerne',
    'roof-tarp-brownsville',
    'roof-tarp-brushy-creek',
    'roof-tarp-bryan',
    'roof-tarp-burleson',
    'roof-tarp-canyon-lake',
    'roof-tarp-carrollton',
    'roof-tarp-cedar-hill',
    'roof-tarp-cedar-park',
    'roof-tarp-celina',
    'roof-tarp-channelview',
    'roof-tarp-cibolo',
    'roof-tarp-cleburne',
    'roof-tarp-cloverleaf',
    'roof-tarp-college-station',
    'roof-tarp-colleyville',
    'roof-tarp-conroe',
    'roof-tarp-converse',
    'roof-tarp-coppell',
    'roof-tarp-copperas-cove',
    'roof-tarp-corinth',
    'roof-tarp-corsicana',
    'roof-tarp-deer-park',
    'roof-tarp-del-rio',
    'roof-tarp-denison',
    'roof-tarp-desoto',
    'roof-tarp-dickinson',
    'roof-tarp-duncanville',
    'roof-tarp-eagle-pass',
    'roof-tarp-edinburg',
    'roof-tarp-ennis',
    'roof-tarp-euless',
    'roof-tarp-farmers-branch',
    'roof-tarp-fate',
    'roof-tarp-flower-mound',
    'roof-tarp-forney',
    'roof-tarp-fresno',
    'roof-tarp-friendswood',
    'roof-tarp-frisco',
    'roof-tarp-fulshear',
    'roof-tarp-galveston',
    'roof-tarp-garland',
    'roof-tarp-georgetown',
    'roof-tarp-grand-prairie',
    'roof-tarp-grapevine',
    'roof-tarp-greenville',
    'roof-tarp-haltom-city',
    'roof-tarp-harker-heights',
    'roof-tarp-harlingen',
    'roof-tarp-horizon-city',
    'roof-tarp-hurst',
    'roof-tarp-irving',
    'roof-tarp-katy',
    'roof-tarp-keller',
    'roof-tarp-kerrville',
    'roof-tarp-killeen',
    'roof-tarp-kingsville',
    'roof-tarp-kyle',
    'roof-tarp-la-porte',
    'roof-tarp-lake-jackson',
    'roof-tarp-lancaster',
    'roof-tarp-laredo',
    'roof-tarp-league-city',
    'roof-tarp-leander',
    'roof-tarp-lewisville',
    'roof-tarp-little-elm',
    'roof-tarp-longview',
    'roof-tarp-lufkin',
    'roof-tarp-mansfield',
    'roof-tarp-marshall',
    'roof-tarp-mcallen',
    'roof-tarp-melissa',
    'roof-tarp-mesquite',
    'roof-tarp-midlothian',
    'roof-tarp-mission',
    'roof-tarp-mission-bend',
    'roof-tarp-missouri-city',
    'roof-tarp-nacogdoches',
    'roof-tarp-new-braunfels',
    'roof-tarp-north-richland-hills',
    'roof-tarp-odessa',
    'roof-tarp-paris',
    'roof-tarp-pasadena',
    'roof-tarp-pearland',
    'roof-tarp-pecan-grove',
    'roof-tarp-pflugerville',
    'roof-tarp-pharr',
    'roof-tarp-plano',
    'roof-tarp-port-arthur',
    'roof-tarp-princeton',
    'roof-tarp-prosper',
    'roof-tarp-richardson',
    'roof-tarp-rockwall',
    'roof-tarp-rosenberg',
    'roof-tarp-round-rock',
    'roof-tarp-rowlett',
    'roof-tarp-royse-city',
    'roof-tarp-sachse',
    'roof-tarp-saginaw',
    'roof-tarp-san-angelo',
    'roof-tarp-san-benito',
    'roof-tarp-san-juan',
    'roof-tarp-san-marcos',
    'roof-tarp-schertz',
    'roof-tarp-seguin',
    'roof-tarp-sherman',
    'roof-tarp-sienna',
    'roof-tarp-socorro',
    'roof-tarp-southlake',
    'roof-tarp-spring',
    'roof-tarp-stephenville',
    'roof-tarp-temple',
    'roof-tarp-terrell',
    'roof-tarp-texarkana',
    'roof-tarp-texas-city',
    'roof-tarp-the-colony',
    'roof-tarp-timberwood-park',
    'roof-tarp-tyler',
    'roof-tarp-university-park',
    'roof-tarp-victoria',
    'roof-tarp-watauga',
    'roof-tarp-waxahachie',
    'roof-tarp-weatherford',
    'roof-tarp-weslaco',
    'roof-tarp-west-odessa',
    'roof-tarp-wichita-falls',
    'roof-tarp-wylie'
];
if (preg_match('#^/service-areas/([a-z0-9-]+)/?$#', $path, $m) && in_array($m[1], $gone, true)) {
    http_response_code(410);
    header('Content-Type: text/html; charset=utf-8');
    readfile(__DIR__ . '/404.html');
    exit;
}

// Legacy WordPress paths.
if (preg_match('#^/(wp-admin|wp-includes|wp-login\.php|xmlrpc\.php|wp-json)(/|$)#', $path)) {
    http_response_code(410);
    exit;
}
if (preg_match('#^/(sitemap_index|page-sitemap|post-sitemap|category-sitemap)\.xml$#', $path)) {
    header('Location: ' . $home . '/sitemap.xml', true, 301);
    exit;
}
if (preg_match('#^/(feed|comments/feed|category/blog)/?$#', $path)) {
    header('Location: ' . $home . '/blog/', true, 301);
    exit;
}

// Directory requested without its trailing slash.
if (substr($path, -1) !== '/' && is_dir(__DIR__ . $path)) {
    header('Location: ' . $home . $path . '/', true, 301);
    exit;
}

http_response_code(404);
header('Content-Type: text/html; charset=utf-8');
readfile(__DIR__ . '/404.html');
