#!/usr/bin/env bash
# Build the deploy branch for rooftarp.com.
#
# Hostinger's Git auto-deployment clones the REPOSITORY ROOT into the website's
# document root. This repository's root is huttoroofs.com, and rooftarp.com
# lives in rooftarp/ -- so pointing Hostinger at a normal branch would serve
# the wrong site.
#
# This script builds an orphan branch (deploy/rooftarp) whose root IS the
# rooftarp.com document root, carrying only files that should be publicly
# served. Source files (build.py, content/, the backup archive) are deliberately
# left out: the backup in particular must never be web-accessible.
#
#   ./make-deploy-branch.sh          # rebuild and push deploy/rooftarp
#   ./make-deploy-branch.sh --local  # rebuild locally, do not push
#
# Run it from anywhere; it locates the repository itself.

set -euo pipefail

SRC_BRANCH="claude/rooftarp-hostinger-connection-980u78"
DEPLOY_BRANCH="deploy/rooftarp"

REPO="$(git -C "$(dirname "${BASH_SOURCE[0]}")" rev-parse --show-toplevel)"
SITE="$REPO/rooftarp"
cd "$REPO"

# Things that are served. Everything else is source and stays out.
SERVE=(
  home.html index.php 404.html sitemap.xml robots.txt .htaccess
  assets
  about blog contact faqs privacy-policy service-areas services sitemap terms-of-use
)

echo "==> Verifying the build is current and valid"
( cd "$SITE" && python3 build.py >/dev/null && python3 validate.py )

STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT

echo "==> Staging servable files"
for item in "${SERVE[@]}"; do
  if [ -e "$SITE/$item" ]; then
    cp -R "$SITE/$item" "$STAGE/"
  else
    echo "    MISSING: $item" >&2
    exit 1
  fi
done

# Search Console verification files, whatever they are named.
for f in "$SITE"/google*.html; do
  [ -e "$f" ] && cp "$f" "$STAGE/"
done

# Belt and braces: nothing here should ever be a source file.
if find "$STAGE" -name '*.py' -o -name '__pycache__' -o -name 'prune-list.txt' | grep -q .; then
  echo "    Source files reached the staging area — aborting." >&2
  exit 1
fi
if [ -e "$STAGE/backup" ]; then
  echo "    The backup archive reached the staging area — aborting." >&2
  exit 1
fi

echo "==> Building $DEPLOY_BRANCH"
SRC_SHA="$(git rev-parse --short "$SRC_BRANCH" 2>/dev/null || git rev-parse --short HEAD)"
WORKTREE="$(mktemp -d)"
trap 'rm -rf "$STAGE" "$WORKTREE"' EXIT

git worktree add --detach "$WORKTREE" >/dev/null 2>&1
(
  cd "$WORKTREE"
  git checkout --orphan "$DEPLOY_BRANCH" >/dev/null 2>&1
  git rm -rf . >/dev/null 2>&1 || true
  # Copy staged files, including dotfiles such as .htaccess.
  cp -R "$STAGE"/. .
  git add -A
  git commit -q -m "Deploy rooftarp.com ($SRC_SHA)

Generated by rooftarp/make-deploy-branch.sh from $SRC_BRANCH.
Document root only: no build scripts, no content sources, no backup archive.
Do not commit here by hand -- this branch is rebuilt from source."
)

git branch -f "$DEPLOY_BRANCH" "$(git -C "$WORKTREE" rev-parse HEAD)" >/dev/null 2>&1 || true
git worktree remove --force "$WORKTREE" >/dev/null 2>&1

COUNT="$(git ls-tree -r --name-only "$DEPLOY_BRANCH" | wc -l | tr -d ' ')"
echo "==> $DEPLOY_BRANCH built: $COUNT files"
git ls-tree -r --name-only "$DEPLOY_BRANCH" | grep -E '^[^/]+$' | sed 's/^/    /'

if [ "${1:-}" = "--local" ]; then
  echo "==> --local given, not pushing"
  exit 0
fi

echo "==> Pushing $DEPLOY_BRANCH"
for i in 1 2 3 4; do
  if git push -f -u origin "$DEPLOY_BRANCH"; then
    echo "==> Done"
    exit 0
  fi
  sleep $((2 ** i))
done
echo "push failed after 4 attempts" >&2
exit 1
