<?php
/**
 * Service pages. Each entry renders at /services/{slug}/ through
 * templates/pages/service.php. Copy is factual and avoids promises about
 * response times, pricing, warranties or credentials.
 */
return [
    'roof-repair' => [
        'name'  => 'Roof Repair',
        'icon'  => 'wrench',
        'image' => 'shingle-damage',
        'card'  => 'Leaks, missing or damaged shingles, flashing failures and other localized problems, assessed and repaired at the source.',
        'title' => 'Roof Repair in Friendswood, TX | Friendswood Roofers',
        'description' => 'Roof repair for Friendswood, TX homes: leaks, damaged shingles, flashing and vent problems. Learn the process and cost factors, then request an estimate.',
        'h1'    => 'Roof Repair in Friendswood, TX',
        'lead'  => 'A small roofing problem rarely stays small. Water that gets past one lifted shingle or a cracked pipe boot can travel along the decking and show up as a ceiling stain several feet away. Our roof repair service is about finding where water or damage actually starts, fixing that point properly and telling you plainly whether the rest of the roof has life left in it.',
        'problems_intro' => 'Repairs are usually the right call when the problem is limited to one area and the surrounding roof is still in serviceable condition. Common repair situations include:',
        'problems' => [
            ['Active or recurring leaks', 'Stains on ceilings or walls, drips in the attic, or damp insulation after heavy rain.'],
            ['Missing, cracked or lifted shingles', 'Often caused by wind, age or fasteners that have backed out over time.'],
            ['Flashing failures', 'Loose, rusted or poorly sealed flashing around chimneys, walls, skylights and valleys.'],
            ['Pipe boots and roof vents', 'Rubber collars around plumbing vents can crack in sun and heat, letting water run down the pipe.'],
            ['Damaged decking in a small area', 'Soft or sagging spots where water has been getting in for some time.'],
        ],
        'scope' => [
            'Locating the source of a leak, not just the spot where it appears inside',
            'Replacing missing, cracked or creased shingles and matching them as closely as available materials allow',
            'Resealing or replacing flashing at walls, chimneys, valleys and roof penetrations',
            'Replacing worn pipe boots, vent covers and similar components',
            'Replacing small sections of damaged decking when the inspection shows it is needed',
            'Photos and a written description of what was found and what was repaired',
        ],
        'process' => [
            ['Tell us what you are seeing', 'Call or send the estimate form with what you have noticed, when it happens and roughly where. Photos taken safely from the ground or inside the house help.'],
            ['Inspection of the problem area', 'We look at the roof surface, flashing and, when accessible, the attic to trace the source.'],
            ['Clear repair recommendation', 'You receive a written description of the problem, the proposed repair and the price before any work begins.'],
            ['Repair and clean-up', 'The repair is completed, debris is removed and we share photos of the finished work.'],
        ],
        'cost_factors' => [
            'How far water has spread and whether decking or underlayment must be replaced',
            'The roofing material and whether matching shingles or panels are still available',
            'Roof pitch, height and how easily the area can be reached safely',
            'Number of penetrations, valleys or wall intersections involved',
            'Whether the problem is one isolated spot or several separate areas',
        ],
        'faqs' => [
            ['Can you repair a roof without replacing it?', 'Often, yes. If the damage is limited to one area and the rest of the roof is in reasonable condition, a targeted repair is usually the sensible option. If an inspection shows widespread wear, we will explain why a repair may only be a short-term fix so you can decide with full information.'],
            ['Will repaired shingles match my existing roof?', 'We aim for the closest available match in color and profile. Older shingle lines are sometimes discontinued, and new shingles can look slightly different from weathered ones at first. We will tell you before the work if an exact match is not possible.'],
            ['What should I do while I wait for a repair?', 'Stay off the roof. Move belongings away from the leak, place a container under drips and, if water is collecting in a bulging ceiling, keep people clear of that area. Take photos for your records.'],
            ['How long does a typical roof repair take?', 'Many single-area repairs are finished in one visit, but timing depends on the size of the repair, materials and weather. We will give you an expected timeframe with your estimate.'],
        ],
        'articles' => ['roof-repair-or-replacement-friendswood', 'roof-inspection-what-to-expect-friendswood'],
        'related'  => ['roof-inspections', 'storm-damage-roof-repair', 'roof-replacement'],
    ],

    'roof-replacement' => [
        'name'  => 'Roof Replacement',
        'icon'  => 'home',
        'image' => 'shingle-bundles-on-roof',
        'card'  => 'Complete tear-off and new roof system when repairs no longer make sense, with clear options for materials and scope.',
        'title' => 'Roof Replacement in Friendswood, TX | Friendswood Roofers',
        'description' => 'Thinking about a new roof in Friendswood, TX? See what a full roof replacement includes, how the process works and what affects cost. Request an estimate.',
        'h1'    => 'Roof Replacement in Friendswood, TX',
        'lead'  => 'Replacing a roof is one of the larger projects a homeowner takes on, so it should start with facts rather than pressure. We look at the condition of the whole roof system, explain whether replacement is truly needed and, if it is, walk you through material options, scope and pricing in writing so you can compare and decide.',
        'problems_intro' => 'Replacement is usually worth discussing when problems are spread across the roof rather than limited to one spot. Signs include:',
        'problems' => [
            ['Widespread wear', 'Curling, cracking or brittle shingles across several slopes, or heavy granule loss in gutters.'],
            ['Repeated leaks in different areas', 'When new leaks keep appearing after repairs, the roof covering may be near the end of its service life.'],
            ['Sagging or soft decking', 'Signs of long-term moisture or structural concerns that need a closer look.'],
            ['Extensive storm damage', 'Damage across many areas of the roof can make full replacement more practical than patching.'],
            ['Planned home improvements', 'Some homeowners replace an aging roof before selling, adding solar or changing materials.'],
        ],
        'scope' => [
            'Removal of existing roofing down to the deck and disposal of old materials',
            'Deck inspection and replacement of damaged sheathing where needed (priced separately and explained in advance)',
            'New underlayment, drip edge and leak barriers at vulnerable areas as specified in your estimate',
            'New flashing, pipe boots and ventilation components appropriate to the roof',
            'Installation of the chosen roofing material following the manufacturer\'s instructions',
            'Magnetic nail sweep, debris removal and a final walkthrough with photos',
        ],
        'process' => [
            ['Inspection and measurements', 'We assess the roof, attic ventilation and decking where visible, and take measurements for an accurate estimate.'],
            ['Written estimate and options', 'You receive a written scope with materials, line items and any conditions, such as possible decking replacement.'],
            ['Scheduling and preparation', 'We agree on a start date, discuss driveway access, materials delivery and how to protect landscaping and belongings.'],
            ['Tear-off and installation', 'The old roof is removed, the deck is checked and the new roof system is installed. Weather can shift the schedule.'],
            ['Clean-up and review', 'We clean the site, check the work and walk you through photos of the completed roof.'],
        ],
        'cost_factors' => [
            'Roof size and the number of slopes, valleys, hips and penetrations',
            'Roof pitch and height, which affect safety equipment and labor',
            'The material and product line you choose',
            'Number of existing layers to remove and the amount of decking that must be replaced',
            'Ventilation upgrades, skylights, chimneys or other details that need new flashing',
            'Permit requirements and any insurance-related documentation you need',
        ],
        'faqs' => [
            ['How do I know if I need a new roof or just a repair?', 'Location and extent matter most. Isolated damage on an otherwise sound roof can usually be repaired. Widespread wear, repeated leaks or damaged decking in several areas usually point toward replacement. Our guide on repair versus replacement explains the trade-offs in more detail.'],
            ['How long does a roof replacement take?', 'Many single-family homes are completed in a few working days, but size, complexity, material deliveries, decking repairs and weather all change the timeline. Your estimate will include an expected schedule.'],
            ['Can new shingles go over my old roof?', 'Overlaying hides the condition of the deck and can shorten the life of the new roof, and many manufacturers and local requirements limit it. We generally recommend a full tear-off so the deck can be inspected, and will explain the reasons for your specific roof.'],
            ['Does insurance pay for roof replacement?', 'That depends entirely on your policy, the cause of damage and your insurer\'s decision. We can document roof conditions with photos, but we cannot promise coverage or negotiate claims on your behalf.'],
        ],
        'articles' => ['roof-repair-or-replacement-friendswood', 'asphalt-shingles-vs-metal-roofing-friendswood-tx', 'how-to-choose-a-roofing-contractor-friendswood'],
        'related'  => ['asphalt-shingle-roofing', 'metal-roofing', 'roof-inspections'],
    ],

    'roof-inspections' => [
        'name'  => 'Roof Inspections',
        'icon'  => 'search',
        'image' => 'worn-shingles-eaves',
        'card'  => 'A documented look at your roof\'s condition, with photos and plain-language notes, before you decide on repairs or replacement.',
        'title' => 'Roof Inspections in Friendswood, TX | Friendswood Roofers',
        'description' => 'Book a roof inspection in Friendswood, TX. Learn what we check, how the visit works and what you receive afterward, then request an estimate.',
        'h1'    => 'Roof Inspections in Friendswood, TX',
        'lead'  => 'A roof inspection gives you a clear picture before you spend money. Whether you have noticed a stain on the ceiling, are buying or selling a home, or simply have not had the roof looked at in a while, an inspection documents the condition of the roof so decisions are based on evidence rather than guesswork.',
        'problems_intro' => 'Homeowners commonly ask for an inspection when:',
        'problems' => [
            ['After severe weather', 'High wind, hail or a tropical storm has passed through and you want to know whether anything changed.'],
            ['Signs of a leak', 'Water stains, musty attic smells or damp insulation without an obvious cause.'],
            ['Buying or selling', 'You want a roofing-focused look in addition to a general home inspection.'],
            ['Aging roof', 'You do not know the roof\'s age or history and want to plan ahead.'],
            ['Before other projects', 'Adding solar panels, gutters or an addition that ties into the roof.'],
        ],
        'scope' => [
            'Exterior roof surface: shingles or panels, fasteners, granule loss and visible damage',
            'Flashing at walls, chimneys, skylights, valleys and roof penetrations',
            'Ridge, soffit and other ventilation components that are visible',
            'Gutters and downspouts as they relate to roof drainage',
            'Attic check for daylight, moisture stains and ventilation concerns, when safely accessible',
            'Photos and written notes describing what we found and any recommended next steps',
        ],
        'process' => [
            ['Schedule the visit', 'Tell us why you want an inspection and anything you have noticed. We confirm a time that works for you.'],
            ['On-site inspection', 'We inspect the roof surface and components, and the attic where accessible. You do not need to go on the roof.'],
            ['Findings review', 'We share photos and explain what is normal wear, what needs attention and what can wait.'],
            ['Written recommendations', 'If work is needed, you receive a written estimate. There is no obligation to proceed.'],
        ],
        'cost_factors' => [
            'Purpose of the inspection, such as general condition, a specific leak or post-storm documentation',
            'Roof size, height and pitch',
            'Attic access and whether interior areas need to be checked',
            'Level of documentation you need, for example for a real estate transaction',
        ],
        'faqs' => [
            ['Do I need to be home for a roof inspection?', 'For an exterior-only inspection it is not always necessary, but attic or interior checks require someone to be home. It also helps to walk us through what you have noticed.'],
            ['Is a roof inspection the same as a home inspection?', 'No. A general home inspection covers the whole house and may only look at the roof from the ground or a ladder. A roof inspection focuses on the roof system in more detail.'],
            ['Will you tell me if nothing needs to be done?', 'Yes. If the roof is in good condition for its age, we will say so and may suggest what to keep an eye on.'],
            ['Can an inspection tell me exactly how many years my roof has left?', 'No one can give a precise number. We can describe the roof\'s current condition and the signs of wear we see, which helps you plan, but the remaining life depends on weather, ventilation, maintenance and the original installation.'],
        ],
        'articles' => ['roof-inspection-what-to-expect-friendswood', 'friendswood-roof-maintenance-checklist'],
        'related'  => ['roof-repair', 'roof-maintenance', 'storm-damage-roof-repair'],
    ],

    'storm-damage-roof-repair' => [
        'name'  => 'Storm Damage Roof Repair',
        'icon'  => 'storm',
        'image' => 'wind-damaged-roof',
        'card'  => 'Assessment and repair after wind, hail, falling limbs or tropical weather, with photo documentation you can keep.',
        'title' => 'Storm Damage Roof Repair in Friendswood, TX | Friendswood Roofers',
        'description' => 'Storm damage roof repair for Friendswood, TX homes after wind, hail or tropical weather. Learn what to do first, what we document and how repairs work.',
        'h1'    => 'Storm Damage Roof Repair in Friendswood, TX',
        'lead'  => 'Friendswood sits close to the upper Texas Gulf Coast, so strong thunderstorms, gusty winds and tropical systems are part of life here. After a storm, roof damage is not always visible from the ground. We inspect the roof, document what we find with photos and explain the repair options so you can make decisions and, if you choose, share the documentation with your insurer.',
        'problems_intro' => 'Storm-related roof problems we commonly look for include:',
        'problems' => [
            ['Wind damage', 'Missing, creased or lifted shingles, loosened ridge caps and displaced flashing.'],
            ['Hail impacts', 'Bruised or cracked shingles, dented metal components and granule loss that can shorten roof life.'],
            ['Fallen limbs and debris', 'Punctures, broken decking or damage to gutters and edges.'],
            ['Wind-driven rain', 'Water forced under shingles or flashing that shows up as new interior leaks.'],
            ['Hidden damage', 'Problems that are only visible on the roof surface or from the attic.'],
        ],
        'scope' => [
            'Storm damage inspection of the roof surface, flashing, vents, edges and gutters',
            'Dated photo documentation of damage you can keep for your records',
            'Temporary protection, such as tarping, when it is safe and appropriate to do so',
            'Repair of damaged shingles, flashing, vents and decking',
            'Full replacement estimates when damage is widespread',
            'A written scope you can share with your insurance company if you decide to file a claim',
        ],
        'process' => [
            ['Make sure everyone is safe', 'Stay away from downed power lines and do not climb onto a wet or damaged roof. Contact emergency services for immediate hazards.'],
            ['Contact us', 'Call or send the estimate form with what happened and what you are seeing. Photos from the ground or inside help us prepare.'],
            ['Inspection and documentation', 'We inspect the roof and record damage with photos and notes.'],
            ['Temporary protection if needed', 'When a roof is open to the weather and it is safe to work, we can discuss temporary measures until permanent repairs are made.'],
            ['Repair or replacement', 'You receive a written estimate. Once approved and scheduled, the work is completed and documented.'],
        ],
        'cost_factors' => [
            'Type and extent of damage, and whether interior water damage is involved',
            'Whether temporary protection is needed before permanent repairs',
            'Material availability and matching for partial repairs',
            'Decking or structural damage discovered once damaged materials are removed',
            'Scheduling demand and weather after a widespread storm',
        ],
        'faqs' => [
            ['Should I call my insurance company or a roofer first?', 'That is your decision, and many homeowners do both. Review your policy and your insurer\'s instructions. An inspection can help you understand whether there is roof damage worth reporting. We do not act as a public adjuster or negotiate claims.'],
            ['Can you guarantee my insurance claim will be approved?', 'No. Coverage decisions belong to your insurance company and depend on your policy. We can provide photos and a written description of the damage we find.'],
            ['Will you waive or cover my deductible?', 'No. Texas law prohibits contractors from paying, waiving or rebating a homeowner\'s insurance deductible, and you should be cautious of anyone who offers to.'],
            ['Can you come out during a storm?', 'Roof work is not safe during lightning, high wind or heavy rain. Inspections and repairs are scheduled once conditions are safe. Call us to discuss timing.'],
            ['Do I need a windstorm inspection?', 'If your home is in the Galveston County part of Friendswood and is insured, or may be insured, through the Texas Windstorm Insurance Association (TWIA), roofing work may need a Texas Department of Insurance windstorm inspection. Check with your insurer or agent before work starts and tell us so it can be planned for.'],
        ],
        'articles' => ['roof-inspection-what-to-expect-friendswood', 'how-to-choose-a-roofing-contractor-friendswood'],
        'related'  => ['roof-repair', 'roof-inspections', 'roof-replacement'],
    ],

    'asphalt-shingle-roofing' => [
        'name'  => 'Asphalt Shingle Roofing',
        'icon'  => 'layers',
        'image' => 'asphalt-shingles-closeup',
        'card'  => 'Installation and repair of the most common residential roofing material, with guidance on shingle types and roof system components.',
        'title' => 'Asphalt Shingle Roofing in Friendswood, TX | Friendswood Roofers',
        'description' => 'Asphalt shingle roof installation and repair in Friendswood, TX. Compare shingle types, see what a full shingle roof system includes and request an estimate.',
        'h1'    => 'Asphalt Shingle Roofing in Friendswood, TX',
        'lead'  => 'Asphalt shingles cover a large share of homes in the Friendswood area because they are widely available, work on most residential roof shapes and come in a broad range of colors and styles. A shingle roof performs best when the whole system, including underlayment, flashing and ventilation, is installed correctly, so that is how we approach every shingle project.',
        'problems_intro' => 'Homeowners usually contact us about asphalt shingles for one of these reasons:',
        'problems' => [
            ['Replacing an aging shingle roof', 'Curling, cracking or granule loss across the roof.'],
            ['Upgrading shingle type', 'Moving from older three-tab shingles to dimensional (architectural) shingles or impact-resistant products.'],
            ['Storm or wind damage', 'Missing or creased shingles that need repair or replacement.'],
            ['Color or curb appeal', 'Changing the look of the home as part of a broader update.'],
            ['Ventilation or heat concerns', 'Hot attics and premature wear that may be linked to ventilation.'],
        ],
        'scope' => [
            'Help choosing between three-tab, dimensional (architectural) and impact-resistant shingle products',
            'Tear-off, deck inspection and replacement of damaged decking where needed',
            'Underlayment, drip edge, starter strips and leak barriers as specified in your estimate',
            'Flashing at walls, chimneys and valleys, plus new pipe boots',
            'Ridge caps and ventilation components matched to the roof',
            'Installation following the shingle manufacturer\'s written instructions',
        ],
        'process' => [
            ['Inspection and goals', 'We look at the current roof and discuss your priorities: budget, appearance, wind or hail resistance and long-term plans.'],
            ['Product options', 'We explain the differences between shingle types and show color options available from suppliers.'],
            ['Written estimate', 'You receive a scope listing the products and components included.'],
            ['Installation', 'The roof is installed as scheduled, weather permitting, and the site is cleaned daily.'],
            ['Final review', 'We walk through the completed work and provide photos and product information for your records.'],
        ],
        'cost_factors' => [
            'Shingle type and product line, for example standard dimensional versus impact-resistant',
            'Roof size, pitch and complexity',
            'Number of layers to remove and decking condition',
            'Ventilation, flashing and accessory components',
            'Permits and any documentation required by your insurer',
        ],
        'faqs' => [
            ['What is the difference between three-tab and architectural shingles?', 'Three-tab shingles are a single flat layer with a uniform pattern. Architectural, or dimensional, shingles are made from laminated layers, which gives a thicker, more textured look. Manufacturers typically rate dimensional products for higher wind resistance than basic three-tab shingles, but ratings vary by product.'],
            ['Are impact-resistant shingles worth it?', 'They are designed to resist hail damage better than standard shingles, and some insurers offer premium discounts for qualifying products. Whether that is worthwhile depends on your budget and policy, so ask your insurer about any discount before choosing.'],
            ['How long do asphalt shingles last in Friendswood?', 'Lifespan depends on the product, installation quality, attic ventilation and how much heat and storm exposure the roof sees. Rather than relying on a single number, an inspection of your roof\'s actual condition is the best guide.'],
            ['Can you match the shingles on my existing roof?', 'For repairs we look for the closest available match. Discontinued products and weathering can make an exact match difficult, and we will tell you before work begins.'],
        ],
        'articles' => ['asphalt-shingles-vs-metal-roofing-friendswood-tx', 'friendswood-roof-maintenance-checklist'],
        'related'  => ['roof-replacement', 'metal-roofing', 'roof-repair'],
    ],

    'metal-roofing' => [
        'name'  => 'Metal Roofing',
        'icon'  => 'shield',
        'image' => 'standing-seam-metal-roof',
        'card'  => 'Standing seam and exposed-fastener metal roofing options, explained honestly so you can weigh cost, appearance and performance.',
        'title' => 'Metal Roofing in Friendswood, TX | Friendswood Roofers',
        'description' => 'Considering a metal roof in Friendswood, TX? Compare standing seam and exposed-fastener panels, learn what affects cost and request an estimate.',
        'h1'    => 'Metal Roofing in Friendswood, TX',
        'lead'  => 'Metal roofing has become a popular choice for homeowners who want a durable roof with a clean, modern look. It is also a bigger upfront investment than most shingle roofs, so it deserves a careful conversation. We explain the main metal roof types, what they are good at and where their limits are, so you can decide whether metal fits your home and budget.',
        'problems_intro' => 'Homeowners usually look at metal roofing when they want:',
        'problems' => [
            ['Long-term durability', 'A roof covering that is often expected to outlast typical asphalt shingles when properly installed and maintained.'],
            ['Wind performance', 'Panel systems that can be engineered for high wind ratings, which matters near the Gulf Coast.'],
            ['Reflective finishes', 'Lighter or coated finishes that reflect more sunlight than dark shingles.'],
            ['A different look', 'The clean lines of standing seam panels on modern, farmhouse or traditional homes.'],
            ['Outbuildings and porches', 'Metal on patios, porches, garages and shops, sometimes paired with a shingle main roof.'],
        ],
        'scope' => [
            'Guidance on standing seam versus exposed-fastener panel systems',
            'Panel material, gauge and finish options from available suppliers',
            'Removal of existing roofing and deck inspection',
            'Underlayment suited to metal roofing, as specified by the panel manufacturer',
            'Trim, flashing, ridge and penetration details designed for metal',
            'Installation following the panel manufacturer\'s instructions',
        ],
        'process' => [
            ['Consultation and inspection', 'We inspect the existing roof and discuss your goals, budget and the look you want.'],
            ['System selection', 'We explain the options for panel type, color and finish, and how each affects cost.'],
            ['Written estimate', 'A detailed scope covers panels, underlayment, trim, flashing and any decking work.'],
            ['Material ordering', 'Metal panels and trim often need to be ordered or fabricated, which affects scheduling.'],
            ['Installation and review', 'The roof is installed as scheduled, weather permitting, and we walk you through the finished work.'],
        ],
        'cost_factors' => [
            'Panel system: standing seam generally costs more than exposed-fastener panels',
            'Metal type, thickness and paint or coating system',
            'Roof size and complexity, including valleys, dormers and penetrations',
            'Tear-off, decking condition and underlayment',
            'Custom trim, flashing and color choices',
            'Lead time for ordering panels and trim',
        ],
        'faqs' => [
            ['Is a metal roof noisy in the rain?', 'With solid decking, underlayment and attic insulation beneath it, most homeowners find a metal roof is not much louder than shingles. Metal installed over open framing, such as on a barn, is noisier.'],
            ['Does a metal roof make a house hotter?', 'Metal itself does not trap heat the way people sometimes expect. Light-colored and reflective coated finishes can reflect more sunlight than dark shingles. Overall attic temperature also depends heavily on ventilation and insulation.'],
            ['Can metal roofing be installed over shingles?', 'Some systems allow it in certain situations, but it hides the condition of the deck and may conflict with manufacturer or local requirements. We usually recommend removal so the deck can be inspected.'],
            ['Is metal roofing worth the higher cost?', 'It depends on how long you plan to stay in the home, your budget and your priorities. Our comparison of asphalt shingles and metal roofing walks through the trade-offs.'],
        ],
        'articles' => ['asphalt-shingles-vs-metal-roofing-friendswood-tx', 'roof-repair-or-replacement-friendswood'],
        'related'  => ['roof-replacement', 'asphalt-shingle-roofing', 'roof-maintenance'],
    ],

    'roof-maintenance' => [
        'name'  => 'Roof Maintenance',
        'icon'  => 'calendar',
        'image' => 'roof-cleaning-maintenance',
        'card'  => 'Routine checks and small fixes that help catch problems early, especially before and after the Gulf Coast storm season.',
        'title' => 'Roof Maintenance in Friendswood, TX | Friendswood Roofers',
        'description' => 'Roof maintenance for Friendswood, TX homes: routine checks, sealant and flashing touch-ups, debris removal and pre-storm-season reviews. Request an estimate.',
        'h1'    => 'Roof Maintenance in Friendswood, TX',
        'lead'  => 'Heat, humidity, heavy rain and the occasional tropical storm all put steady stress on a roof. Routine maintenance helps catch small issues, like a cracked pipe boot or a loose piece of flashing, before they turn into leaks. It also gives you an up-to-date record of the roof\'s condition.',
        'problems_intro' => 'Maintenance visits often address:',
        'problems' => [
            ['Debris build-up', 'Leaves and branches in valleys and gutters that hold moisture and slow drainage.'],
            ['Aging sealants', 'Dried or cracked sealant around flashing, vents and fasteners.'],
            ['Small component failures', 'Cracked pipe boots, loose vent caps and lifted shingles.'],
            ['Overhanging limbs', 'Branches that scrape the roof surface or could fall in high wind.'],
            ['Algae streaks and growth', 'Dark staining that is common in humid climates and is mostly cosmetic but worth monitoring.'],
        ],
        'scope' => [
            'Visual check of the roof surface, flashing, vents and edges',
            'Clearing debris from roof valleys and gutters where included in the estimate',
            'Resealing exposed fasteners and flashing details where appropriate',
            'Replacing small worn components such as pipe boots',
            'Securing or replacing a small number of loose or damaged shingles',
            'Photos and notes on items to watch or plan for',
        ],
        'process' => [
            ['Choose a timing', 'Many homeowners schedule maintenance in spring, before the June start of hurricane season, and again after major storms.'],
            ['Maintenance visit', 'We check the roof and complete the agreed small tasks.'],
            ['Report', 'You receive photos and notes, plus a separate estimate for any larger repairs we find. Nothing extra is done without your approval.'],
        ],
        'cost_factors' => [
            'Roof size, height and pitch',
            'Amount of debris and gutter cleaning included',
            'Number of small repairs or replacement parts needed',
            'Roof material and accessibility',
        ],
        'faqs' => [
            ['How often should a roof be maintained?', 'A yearly check is a reasonable baseline for many homes, with additional checks after severe weather. Older roofs or homes with many overhanging trees may benefit from more frequent attention.'],
            ['Can I do roof maintenance myself?', 'Homeowners can do a lot from the ground and inside the house: watch for ceiling stains, check the attic with a flashlight, keep gutters flowing from a stable ladder if you are comfortable doing so, and trim trees with professional help. Leave work on the roof surface to people with proper safety equipment.'],
            ['Should I pressure-wash my roof?', 'High-pressure washing can strip granules from asphalt shingles. If staining bothers you, ask about low-pressure cleaning methods and check the shingle manufacturer\'s guidance.'],
            ['Does maintenance affect my roof warranty?', 'Some manufacturer warranties expect reasonable maintenance. Review the warranty documents for your specific roof, and keep records and photos of maintenance visits.'],
        ],
        'articles' => ['friendswood-roof-maintenance-checklist', 'roof-inspection-what-to-expect-friendswood'],
        'related'  => ['roof-inspections', 'roof-repair', 'storm-damage-roof-repair'],
    ],
];
